### ISSUE TITLE
Lossy-compressed fast5 files have the same size as the original (uncompressed) files.

### ISSUE THREAD

**Issue by merceod** [shubhamchandak94/lossy_compression_evaluation#3]
Hello! I tried running the `generate_lossy_fast5.py` script (in the same manner as shown in your `run_exp_generate_fast5.sh` script) to lossy-compress some single-read fast5 files I have. While the .tsv that was produced showed compressed sizes that were smaller than the original size, when I ran `ls -l `, I noticed that the sizes of the resulting compressed files were the same as the original fast5 input files. I also ran the `stat` and `du -hs` commands and still noticed the same file size for the input and output despite the .tsv summary file showing a smaller compressed size. Just to confirm that there was nothing wrong with my dataset, I used the E.coli dataset that you provide as an example (in `DATASETS.md`). I followed the same steps as you highlighted and ran the script on it and still observed the same issue - the output files are the same size as the input, despite the .tsv file showing smaller compressed sizes. This issue comes up for both compressors,  LFZip and SZ. Would really appreciate it if you could provide some insight into why this may be the case.

**Comment by shubhamchandak94** [comment]
Hi, the idea of generating lossy fast5 file is to lossily compress the signal files and then reconstruct by decompressing, and then creating a new fast5 that holds the reconstruction. So you could store the lossy compressed file as your storage/transmission and then decompress it back when you want to use. In this case if the original and the reconstruction fast5 hold the signal in raw form their sizes will be identical, we are just replacing the signal with a quantized version that we know is very compressible. 

Eventually we would want to integrate one of these lossy compression algorithms into the fast5 format and tooling so you never need to decompress the file unnecessarily
